PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/fly/IQ4511/bin,system/bin)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/fly/IQ4511/etc,system/etc)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/fly/IQ4511/lib,system/lib)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/fly/IQ4511/vendor,system/vendor)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/fly/IQ4511/xbin,system/xbin)
